name: replicate-ci

on:
  pull_request:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      BASE_IMAGE: 'daanelson/real-esrgan-a100'
      PUSH_DEST: 'daanelson/real-esrgan-staging'

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install yolo
      run: |
        sudo curl -o /usr/local/bin/yolo -L "https://github.com/replicate/yolo/releases/latest/download/yolo_$(uname -s)_$(uname -m)"
        sudo chmod +x /usr/local/bin/yolo

    - name: what changed
      id: files
      run: |
        echo "FILES_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})" >> $GITHUB_ENV

    - name: push model
      env:
       REPLICATE_API_TOKEN: ${{secrets.REPLICATE_API_TOKEN}}
      run: |
        echo "pushing changes from $BASE_IMAGE to $PUSH_DEST"
        echo "changed files: $GITHUB_ENV"
        yolo push --base $BASE_IMAGE --dest $PUSH_DEST $GITHUB_ENV

    # - name: test model
    #   -- just run some http tests
    #   -- borrow template from SDXL
    #   -- pass in some flag s.t. we're testing in prod
